# Solving Simple Linear Systems Using Python

## Objective
+ Learn how to solve linear systems using Python.

## Where do linear systems come from?
Linear systems of equations occur in every single problem of statics, in particular, and mechanics, in general.
Let us use [Problem 3.D.12](https://youtu.be/4mKf48zp-PY) of our lecturebook as a specific example of where the linear system comes from.
Please watch the video.
Using the static equilibrium equations, we find three equations containing three uknowns (assume that $W=1$).
In particular, we have:
$$
\begin{array}{ccc}
-0.63\cdot F_{CA} + 0\cdot F_{CB} + 0.79\cdot F_{CD} &=& 0,\\
0.63\cdot F_{CA} + 0.8\cdot F_{CB} + 0.20\cdot F_{CD} &=& 1,\\
0.43\cdot F_{CA} - 0.6\cdot F_{CB} + 0.59\cdot F_{CD} &=& 0.
\end{array}
$$
At this point, you need to dust off your linear algebra knowledge and notice that this system corresponds can be written using a matrix-vector multiplication:
$$
\left(
\begin{array}{ccc}
-0.63 & 0 & 0.79\\
0.63 & 0.8 & 0.2\\
0.43 & -0.6 & 0.59
\end{array}
\right) \cdot 
\left(
\begin{array}{c}
F_{CA}\\
F_{CB}\\
F_{CD}
\end{array}
\right)=
\left(
\begin{array}{c}
0\\
1\\
0
\end{array}
\right).
$$
We clearly see that this is a matrix-vector equation of the form:
$$
\mathbf{A} \cdot \mathbf{x} = \mathbf{b}.
$$
Let's set this system up in Python.

In [1]:
# Load the necessary modules - Always do this before you start
import numpy as np # Module for numerical linear algebra
# Create the matrix A
A = np.array([[-0.63, 0, 0.79],
              [0.63, 0.8, 0.2],
              [0.43, -0.6, 0.59]])
b = np.array([0, 1, 0])
print('Matrix A:')
print(A)
print('Vector b:')
print(b)

Matrix A:
[[-0.63  0.    0.79]
 [ 0.63  0.8   0.2 ]
 [ 0.43 -0.6   0.59]]
Vector b:
[0 1 0]


## Solving the linear system
The solution of the linear system is:
$$
\mathbf{x} = \mathbf{A}^{-1}\mathbf{b},
$$
if the matrix inverse, $\mathbf{A}^{-1}$, exists.
This will be the case when you have a *nice* problem.
The problem is *nice* when:
+ you have the same number of uknown as equations, i.e., the matrix $\mathbf{A}$ is a square matrix.
+ the [determinant](https://en.wikipedia.org/wiki/Determinant) of the matrix $\mathbf{A}$ is not zero.

Despite the simplicity of the solution using the matrix inverse, **YOU SHOULD NEVER USE**.
I repeat: **YOU SHOULD NEVER USE THE MATRIX INVERSE TO SOLVE A LINEAR SYSTEM**.
**NEVER!!!**
Why? Because you will get larger numerical errors than doing the right thing.
What is the right thing? This is a question for an other course.
In Python, you just need to do this:

In [2]:
x = np.linalg.solve(A, b)
print('Solution x:')
print(x)

Solution x:
[0.50246995 0.75412895 0.40070388]
